pipelines:
  default:
    - step:
        name: Build and test
        services:
          - docker
        script:
          - make --version
          - make django
          - docker run --entrypoint="" --rm tlrh314/atlas-web:local python --version
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_ACCESS_TOKEN_TLRH314
