version: '3.8'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

x-django: &django
  image: docker.gitlab.gwdg.de/solve/atlas-web:production
  restart: always
  depends_on:
    - postgres
    - redis
  volumes:
    - ./nfs:/nfs
  env_file:
    - ./.envs/.production/.django
    - ./.envs/.production/.postgres

services:
  django:
    <<: *django
    container_name: django
    command: ["/start"]

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: docker.gitlab.gwdg.de/solve/atlas-web:postgres
    restart: always
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: docker.gitlab.gwdg.de/solve/atlas-web:traefik
    restart: always
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:5.0
    restart: always

  celeryworker:
    <<: *django
    entrypoint: [""]
    command: ["/start-celeryworker"]

  celerybeat:
    <<: *django
    entrypoint: [""]
    command: ["/start-celerybeat"]

  flower:
    <<: *django
    entrypoint: [""]
    command: ["/start-flower"]

networks:
  default:
    name: atlas
