# Generated by Django 3.0.11 on 2020-11-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Has the User been Validated'),
        ),
    ]
