# Generated by Django 3.0.11 on 2020-11-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Unique identifier for this simulation. This is auto-set on save.', max_length=42, unique=True, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
            ],
        ),
        migrations.CreateModel(
            name='AtlasSimulationInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(help_text='Path to the simulation input folder. This is auto-set on save.', max_length=100, verbose_name='Folder')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
            ],
        ),
        migrations.CreateModel(
            name='AtlasSimulationOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(help_text='Path to the simulation output folder. This is auto-set on save.', max_length=100, verbose_name='Folder')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
            ],
        ),
        migrations.CreateModel(
            name='AtlasSimulationSlurmJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobscript', models.CharField(help_text='Path to the simulation jobscript. This is auto-set on save.', max_length=100, verbose_name='Folder')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Queued'), (2, 'Starting'), (3, 'Running'), (4, 'Paused'), (5, 'Failed'), (6, 'Interrupted'), (7, 'Cancelled'), (8, 'Retried')], default=0, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
            ],
        ),
    ]
