# Generated by Django 3.0.11 on 2020-11-25 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlassimulationslurmjob',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_changed_simulationlurmjobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atlassimulationslurmjob',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slurmjob', to='simulation.AtlasSimulation'),
        ),
        migrations.AddField(
            model_name='atlassimulationoutput',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_changed_simulationoutputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atlassimulationoutput',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='simulation.AtlasSimulation'),
        ),
        migrations.AddField(
            model_name='atlassimulationinput',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_changed_simulationinputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atlassimulationinput',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='simulation.AtlasSimulation'),
        ),
        migrations.AddField(
            model_name='atlassimulation',
            name='access_list',
            field=models.ManyToManyField(blank=True, related_name='has_access_to_simulations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atlassimulation',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_changed_simulations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atlassimulation',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations_started', to=settings.AUTH_USER_MODEL),
        ),
    ]
